apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cluster.x-k8s.io/provider: kubevirt
    cluster.x-k8s.io/v1alpha1: v1alpha1
    cluster.x-k8s.io/v1alpha2: v1alpha1
    cluster.x-k8s.io/v1alpha3: v1alpha1
    cluster.x-k8s.io/v1alpha4: v1alpha1
    cluster.x-k8s.io/v1beta1: v1alpha1
    control-plane: controller-manager
  name: capk-controller-manager
  namespace: capk-system
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/provider: kubevirt
      cluster.x-k8s.io/v1alpha1: v1alpha1
      cluster.x-k8s.io/v1alpha2: v1alpha1
      cluster.x-k8s.io/v1alpha3: v1alpha1
      cluster.x-k8s.io/v1alpha4: v1alpha1
      cluster.x-k8s.io/v1beta1: v1alpha1
      control-plane: controller-manager
  template:
    metadata:
      labels:
        cluster.x-k8s.io/provider: kubevirt
        cluster.x-k8s.io/v1alpha1: v1alpha1
        cluster.x-k8s.io/v1alpha2: v1alpha1
        cluster.x-k8s.io/v1alpha3: v1alpha1
        cluster.x-k8s.io/v1alpha4: v1alpha1
        cluster.x-k8s.io/v1beta1: v1alpha1
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image:
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --leader-elect
        - --metrics-bind-addr=127.0.0.1:8080
        - --feature-gates=MachinePool=false
        command:
        - /manager
        env:
        - name: NO_PROXY
          value: 127.0.0.1,localhost
        image: 16.182.16.160:32000/capk-manager-amd64:dev
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        - containerPort: 9440
          name: healthz
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: healthz
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        - mountPath: /var/run/docker.sock
          name: dockersock
      serviceAccountName: capk-manager
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: capk-webhook-service-cert
      - hostPath:
          path: /var/run/docker.sock
        name: dockersock